name: "pre-commit"
on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    name: "Run Terraform pre-commit checks"
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install pre-commit and dependencies
        shell: bash
        run: |
          pip install pre-commit

          curl -sSLo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-$(uname)-amd64.tar.gz
          sudo tar -xzf terraform-docs.tar.gz -C /usr/bin/ terraform-docs
          rm terraform-docs.tar.gz 2> /dev/null

          curl -sSL "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" > tflint.zip
          sudo unzip -qq tflint.zip tflint -d /usr/bin/
          rm tflint.zip 2> /dev/null

      - name: Run pre-commit
        shell: bash
        run: pre-commit run --all-files --color always --show-diff-on-failure
