name: "pre-commit"
on:
  push:
  pull_request:

jobs:
  pre-commit:
    name: "Run Terraform pre-commit checks"
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install pipenv
        run: |
          pip install pre-commit==2.20.0

      - name: Install pre-commit dependencies
        run: |
          curl -Lo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-$(uname)-amd64.tar.gz && tar -xzf terraform-docs.tar.gz && chmod +x terraform-docs && sudo mv terraform-docs /usr/bin/

      - name: terraform fmt
        run: pre-commit run terraform_fmt --color=always --show-diff-on-failure --all-files

      - name: terraform validate
        run: pre-commit run terraform_validate --color=always --show-diff-on-failure --all-files
